#Stark County Cities, Villages, Townships, etc.


urar_fields = [
    "File #",
    "Property Address",
    "City",
    "Zip Code",
    "Borrower",
    "Owner of Public Record",
    "Legal Description",
    "Assessor's Parcel #",
    "R.E. Taxes $",
    "Neighborhood Name",
    "Map Reference",
    "Census Tract"
    "Special Assessments $",
    "Lender/Client",
    "Is the subject property currently offered for sale or has it been offered for sale in the twelve months prior to the effective date of the appraisal?"
    "Report data source(s) used, offering price(s), and date(s).",
    "Dimensions: Frontage",
    "Dimensions: Depth",
    "Area",
    "FEMA Flood Zone",
    "FEMA Map No.",
    "FEMA Map Date",
    "# of Stories",
    "Design (Style)",
    "Year Built",
    "My research did / did not reveal any prior sales or transfers of the subject property for the three years prior to the effective date of this appraisal.",
    "Date of Prior Sale/Transfer",
    "Price of Prior Sale/Transfer",
    "Effective Date of Data Source(s)",
]

cities = [
    "North Canton", # Cities with duplicate words first
    "East Canton",
    "Canton",
    "North Lawrence",
    "Lawrence",
    "Alliance",
    "Avondale",
    "Beach City",
    "Bethlehem",
    "Brewster",
    "Cairo",
    "Canal Fulton",
    "Crystal Springs",
    "East Greenville",
    "East Sparta",
    "Freeburg",
    "Greentown",
    "Hartville",
    "Hills and Dales",
    "Jackson",
    "Justus",
    "Lake",
    "Lexington",
    "Limaville",
    "Louisville",
    "Magnolia",
    "Mapleton",
    "Marchand",
    "Marlboro",
    "Massillon",
    "Maximo",
    "McDonaldsville",
    "Meyers Lake",
    "Middlebranch",
    "Minerva",
    "Navarre",
    "New Baltimore",
    "New Franklin",
    "Newman",
    "Nimishillen",
    "North Industry",
    "Osnaburg",
    "Paris",
    "Perry",
    "Perry Heights",
    "Pigeon Run",
    "Pike",
    "Plain",
    "Richville",
    "Robertsville",
    "Sandy",
    "Sippo",
    "Sugar Creek",
    "Tuscarawas",
    "Uniontown",
    "Waco",
    "Washington",
    "Waynesburg",
    "Wilmot",
 ]

#Stark County Zip Codes
zipCodes = [
    "44601",
    "44608",
    "44613",
    "44614",
    "44626",
    "44630",
    "44632",
    "44640",
    "44641",
    "44643",
    "44646",
    "44647",
    "44648",
    "44650",
    "44652",
    "44657",
    "44662",
    "44666",
    "44669",
    "44670",
    "44685",
    "44688",
    "44689",
    "44701",
    "44702",
    "44703",
    "44704",
    "44705",
    "44706",
    "44707",
    "44707",
    "44708",
    "44709",
    "44709",
    "44710",
    "44711",
    "44714",
    "44718",
    "44718",
    "44720",
    "44720",
    "44721",
    "44730",
    "44730",
    "44735",
]


hoods = [
	['Canton NW','1'],
	['Canton NE','2'],
	['Canton SW','3'],
	['Canton SE','4'],
	['North Canton','5'],
	['Plain','6'],
	['Jackson','7'],
	['Perry','8'],
	['Massillon','9'],
	['Tuslaw','10'],
	['Fairless','11'],
	['Canal Fulton','12'],
	['Louisville','13'],
	['Tusky Valley','14'],
	[[
		'Lake',
		'Hartville',
		'Uniontown'],
	'15'],
	[[
		'Osnaburg',
		'East Canton'],
	'16'],
	['Canton South','17'],
	['Sandy Valley','18'],
	['Alliance','19'],
	['Marlington','20'],
	['Minerva','21'],
	['Sebring West Branch','22'],
	['Northwest','23'],
]
